const S={online:true,shutdown:null,queue:[],user:null,current:null,epic:false,ends:null};const $=x=>document.getElementById(x);
function render(){if(S.user){$('login').classList.add('hidden');$('user').classList.remove('hidden');$('welcome').textContent='Welcome, '+S.user.name;$('epic').textContent=S.epic?'Connected':'Not connected';let i=S.queue.indexOf(S.user.id);$('pos').textContent=i<0?'—':'#'+(i+1);$('status').textContent=S.current?.id===S.user.id?'Cloud session active':i>=0?'Waiting for a server':'Not in queue';$('session').classList.toggle('hidden',S.current?.id!==S.user.id)}$('badge').textContent=S.online?'● Server online':'● Server offline';$('aserver').textContent=S.online?'Online':'Offline';$('aqueue').textContent=S.queue.length;$('active').textContent=S.current?S.current.name:'None';$('cancel').classList.toggle('hidden',!S.shutdown);$('shutdown').classList.toggle('hidden',!!S.shutdown);let n=$('notice');if(S.shutdown){let t=Math.max(0,S.shutdown-Date.now()),m=Math.floor(t/60000),s=Math.floor(t/1000)%60;n.classList.remove('hidden');n.innerHTML='⚠️ <b>NOVOS Cloud Gaming is shutting down in '+m+':'+String(s).padStart(2,'0')+'.</b><br>Your queue position will be preserved while the service is paused.'}else n.classList.add('hidden')}
function assign(){if(S.online&&!S.shutdown&&!S.current&&S.queue.length){let id=S.queue.shift();S.current={id,name:S.user&&S.user.id===id?S.user.name:'Queue user'};S.ends=Date.now()+3600000}}
$('loginBtn').onclick=()=>{S.user={id:'u'+Date.now(),name:'NOVOS Player'};S.queue.push(S.user.id);assign();render()};
$('epicBtn').onclick=()=>{S.epic=!S.epic;render()};
$('leave').onclick=()=>{S.queue=S.queue.filter(x=>x!==S.user.id);render()};
$('end').onclick=()=>{S.current=null;S.ends=null;assign();render()};
$('shutdown').onclick=()=>{S.shutdown=Date.now()+Number($('mins').value)*60000;render()};
$('cancel').onclick=()=>{S.shutdown=null;render()};
$('toggle').onclick=()=>{S.online=!S.online;if(!S.online){S.shutdown=null;S.current=null;S.ends=null}else assign();render()};
$('back').onclick=()=>{$('admin').classList.add('hidden');$('user').classList.remove('hidden')};
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='a'){e.preventDefault();$('admin').classList.toggle('hidden');$('user').classList.toggle('hidden');$('login').classList.add('hidden')}});
setInterval(()=>{if(S.shutdown&&Date.now()>=S.shutdown){S.shutdown=null;S.online=false;S.current=null;S.ends=null}if(S.ends&&Date.now()>=S.ends){S.current=null;S.ends=null;assign()}render();},1000);render();